### ISSUE TITLE
中間振り返り(12/14)のときのまとめ

### ISSUE THREAD

**Issue by matsubara0507** [mixi18-eng1/mixi18-eng1#13]
当日の資料
https://drive.google.com/file/d/1QoJ6uA6WZUEe2Z4-wcKB50jC08rFBzv2/view
## チーム賞について
1. チームとして高い達成率をキープしていること
2. チームメンバー同士のコミュニケーションが活発なこと
3. フィードバックが有効に作用し、お互いにいい影響を与えていること

### Keep
- PR を使った振り返り方法は良かった

### Problem
- 書くことが無いときはつらいよね
- 研究忙しいのは分かってる

### Try
- ミクアカに直接関係ない事でも書こう
- 研究の話でもいいんじゃないかな

## その他
- Slack の各位チャンネルにもっと情報投げた方が
    - GitHub 連携して流すとか
    - 「なんかみんなやってるなぁ」となって焦る(いい意味で影響しあう)

**Comment by matsubara0507** [comment]
取りあえず記憶をたどって書き出した。
追加・修正などあったら言って or 直接直していいよ。
12/14 に話してなくても、今思えばってのがあればコメントください。

**Comment by yuta0428** [comment]
資料URL追加しといた
サクッと見返したい用に
![12 -40](https://user-images.githubusercontent.com/12966452/34316068-e9543126-e7d0-11e7-9d60-96792187d37a.jpg)
![12 -43](https://user-images.githubusercontent.com/12966452/34316069-ebf4f776-e7d0-11e7-8012-64a5c410872f.jpg)
